[workspace.package]
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/iamipanda/ygopru"
description = "A Rust rewrite of the YGOPro duel server."

[workspace.dependencies]
ygopro = { path = "./ygopro", default-features = false }
ygopro-data = { path = "./ygopro-data", default-features = false }
ygopro-handler = { path = "./ygopro-handler", default-features = false }
ygopro-core-wrapper = { path = "./ygopro-core-wrapper", default-features = false }
ygopro-derive = { path = "./ygopro-derive" }
ygopro-external-server-bridge = { path = "./ygopro-external-server-bridge", default-features = false }

[workspace]
default-members = ["ygopro"]
resolver = "2"
members = [
    "ygopro-data",
    "ygopro-derive",
    "ygopro-core-wrapper",
    "ygopro-handler",
    "ygopro",
    "ygopro-toolkits",
    "ygopro-external-server-bridge"
]

[profile.release]
lto = true
strip = true
opt-level = 'z'
