[package]
name = "ygopro-data"
version = "0.1.0"
edition = "2024"


[dependencies]
binrw = "0.13"
bitflags = "2.4"
encoding_rs = "0.8"
lzma-rs = "0.3"
num_enum = "0.7"
thiserror = "1"
rusqlite = { version = "0.39", features = ["bundled"], optional = true }
ygopro-derive = { path = "../ygopro-derive" }
bytes = "1.11.1"
modular-bitfield = "0.13.1"

[build-dependencies]
syn = "1.0"
darling = "0.14"

[features]
default = ["card"]
card=["dep:rusqlite"]
