[package]
name = "ygopro-external-mobile-bridge"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
repository.workspace = true
description = "A FFI wrapper for adapting ygopro to ygomobile."
keywords = ["ygopro"]

[lib]
name = "ygoserver"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
ygopro.workspace = true

hashbrown = "0.17"
jni = "0.21"
parking_lot = { version = "0", features = ["arc_lock", "send_guard"] }

[features]
default = ["card", "zip"]
card = ["ygopro/card"]
zip = ["ygopro/zip"]
